export const PERMISSIONS = {
  SEARCH_TRANSACTION: 'ROLE_SEARCH_TRANSACTION',
  CREATE_TRANSACTION: 'ROLE_CREATE_TRANSACTION',
  REMOVE_TRANSACTION: 'ROLE_REMOVE_TRANSACTION',
  SEARCH_PERSON: 'ROLE_SEARCH_PERSON',
  CREATE_PERSON: 'ROLE_CREATE_PERSON',
} as const

export type Permission =
  (typeof PERMISSIONS)[keyof typeof PERMISSIONS]
